name: Go Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.ref == 'refs/heads/main' && github.repository == 'gitbroskie/gitbroski'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install semantic-release
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release

      - name: Get latest release tag
        id: get_tag
        run: |
          RELEASE_TAG=$(git describe --tags --abbrev=0)
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          VERSION=${RELEASE_TAG#v}  # remove leading "v"
          echo "Updating package.json to version $VERSION"
          jq --arg v "$VERSION" '.version=$v' package.json > package.tmp.json
          mv package.tmp.json package.json
